language: bash
branches:
  only:
  - master
before_install: bash etc/ci-setup.sh
install: true
script: /tmp/testrunner/bin/run -c . && bash etc/hatchet.sh spec/
after_script: if [ -n "$HEROKU_API_KEY" ]; then heroku keys:remove $USER@`hostname`; fi
env:
  global:
  - IS_RUNNING_ON_TRAVIS=true
  - SHUNIT_HOME="/tmp/shunit2-2.1.6"
  matrix:
  - HEROKU_TEST_STACK="heroku-16"
  - HEROKU_TEST_STACK="heroku-18"
